---
# Terraform Vars
ingress_nginx_external_tfvars:
  namespace: "ingress-external"
  chart:
    repository: "https://kubernetes.github.io/ingress-nginx"
    version: "4.8.3"
    values_files:
    - helm_values_ingress_nginx_external.yml
# Auxiliary variables
ingress_nginx_external_ClassResource_name: "nginx-external"
# Helm Chart values
ingress_nginx_external_helm_values:
  controller:
    tolerations: "{{ default_tolerations }}"
    nodeSelector:
      kubernetes.io/arch: arm64
    ingressClassResource:
      name: "{{ ingress_nginx_external_ClassResource_name }}"
      controllerValue: "k8s.io/external-ingress-nginx"
    replicaCount: "1"
    service:
      externalTrafficPolicy: "Local"
      ipFamilies:
      - IPv6
      annotations:
        cloud.google.com/neg: '{"exposed_ports": {"80":{"name": "http"}, "443":{"name": "https"}}}'
    # -- For backwards compatibility with ingress.class annotation, use ingressClass.
    # Algorithm is as follows, first ingressClassName is considered, if not present, controller looks for ingress.class annotation
    ingressClass: "{{ ingress_nginx_external_ClassResource_name }}"
    admissionWebhooks:
      patch:
        tolerations: "{{ default_tolerations }}"
        nodeSelector:
          kubernetes.io/arch: arm64
  defaultBackend:
    tolerations: "{{ default_tolerations }}"
    nodeSelector:
      kubernetes.io/arch: arm64
