---
# Terraform Vars
argocd_tfvars:
  namespace: "argocd"
  chart:
    repository: "https://argoproj.github.io/argo-helm"
    version: "5.52.1"
    values_files:
    - helm_values_argocd.yml
  applicationSet:
    base:
      name: base
      repoURL: https://github.com/cloudinterplay/poc-gke-arm-based-apps.git
# Auxiliary variables
argocd_hostname: "{{ 'argocd' if inventory_hostname == 'main' else 'argocd-%s' | format(inventory_hostname) }}"
# Helm Chart values
argocd_helm_values:
  server:
    tolerations: "{{ default_tolerations }}"
    nodeSelector:
      kubernetes.io/arch: arm64
    extraArgs:
      - --insecure
    ingress:
      ingressClassName: "nginx-external"
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        external-dns.alpha.kubernetes.io/hostname: "{{ argocd_hostname }}.{{ dns_zone }}."
      hosts:
      - "{{ argocd_hostname }}.{{ dns_zone }}"
      tls:
      - hosts:
        - "{{ argocd_hostname }}.{{ dns_zone }}"
        secretName: certificate-tls
  configs:
    cm:
      url: "https://{{ argocd_hostname }}.{{dns_zone}}"
      admin.enabled: false
      dex.config: |
        connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: $github-oauth:clientId
            clientSecret: $github-oauth:clientSecret
            orgs:
            - name: cloudinterplay
    rbac:
      policy.csv: "{{ policy_csv }}"
    repositories:
      poc-gke-argocd-apps:
        url: https://github.com/cloudinterplay/poc-gke-argocd-apps.git
  redis:
    tolerations: "{{ default_tolerations }}"
    nodeSelector:
      kubernetes.io/arch: arm64
  dex:
    tolerations: "{{ default_tolerations }}"
    nodeSelector:
      kubernetes.io/arch: arm64
  controller:
    tolerations: "{{ default_tolerations }}"
    nodeSelector:
      kubernetes.io/arch: arm64
  notifications:
    tolerations: "{{ default_tolerations }}"
    nodeSelector:
      kubernetes.io/arch: arm64
  repoServer:
    tolerations: "{{ default_tolerations }}"
    nodeSelector:
      kubernetes.io/arch: arm64
policy_csv: |-
  g, cloudinterplay:Contributors, role:admin
