---
# Terraform Vars
external_dns_tfvars:
  namespace: "external-dns"
  chart:
    repository: "https://kubernetes-sigs.github.io/external-dns"
    version: "1.13.1"
    values_file: helm_values_external_dns.yml
# Helm Chart values
external_dns_helm_values:
  extraArgs:
  - --google-project={{ dns_project_id }}
  provider: google
  domainFilters:
  - "{{ dns_zone }}"
  tolerations: "{{ default_tolerations }}"
  nodeSelector:
    kubernetes.io/arch: arm64
