---
# Overridable variables for parameterizing environments
# Variables related to GKE cluster it-self
gke_name: "poc-gke-{{ inventory_hostname }}"
gke_zone: ["us-central1-b"]
gke:
  cluster:
    name: "{{ gke_name }}"
    description: "GKE Cluster {{ gke_name }}"
    location: "us-central1-a"
    release_channel:
      enable: false
    addons_config:
      gcp_filestore_csi_driver_config:
        enabled: false
    ip_allocation_policy:
      cluster_ipv4_cidr_block: "{{ gke_cluster_ipv4_cidr_block }}"
      services_ipv4_cidr_block: "{{ gke_services_ipv4_cidr_block }}"
    master_authorized_networks_config:
      cidr_blocks:
      - cidr_block: "0.0.0.0/0"
        display_name: "Home"
    private_cluster_config:
      enable_private_endpoint: false
      enable_private_nodes: true
      master_ipv4_cidr_block: "{{ gke_master_ipv4_cidr_block }}"
    node_config:
      enable: true
  node_pools:
  - name: "tau"
    autoscaling:        
      min_count: "1"
      max_count: "2"
    node_config:
      machine_type: "t2a-standard-2"
      disk_size_gb: "11"
      disk_type: "pd-standard"
      spot: true
