---
name: "GKE Manage"
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
    inputs:
      action:
        description: "Plan, Apply or Destroy"
        default: plan
        type: choice
        options:
        - plan
        - apply
        - destroy
  push:
    paths:
    - 'group_vars/*'
    - 'host_vars/*'
    - '**.yaml'
    - '**.yml'
env:
  TF_IN_AUTOMATION: 'true'
jobs:
  config:
    name: Generate configuration
    runs-on: 'ubuntu-latest'
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9' 
    - name: Install Ansible 2.13
      run: pip install "ansible-core<=2.13"
    - name: Generate Terraform vars and Backend
      run: ansible-playbook -i inventory.yml --limit ${{ github.ref_name }} preparing.yml
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: terraform-artifacts
        path: structure/terraform/*
        retention-days: 2
  plan:
    if: contains(fromJson('["plan", "apply"]'), github.event.inputs.action)
    needs: config
    uses: ./.github/workflows/workflow.yml
    with:
      action: 'plan'
      working-directory: "structure/terraform"
    secrets: inherit
  apply:
    if: github.event.inputs.action == 'apply'
    needs: plan
    uses: ./.github/workflows/workflow.yml
    with:
      action: 'apply'
      working-directory: "structure/terraform"
    secrets: inherit
  destroy:
    if: github.event.inputs.action == 'destroy'
    needs: config
    uses: ./.github/workflows/workflow.yml
    with:
      action: 'destroy'
      working-directory: "structure/terraform"
    secrets: inherit
